---
title: "Práctica12Anotación"
format: 
  html:
    embed-resources: true
    
engine: knitr
---

# Datos

Las secuencias que vamos a anotar son el ensamblaje obtenido en la práctica anterior, que voy a suponer que se encuentran en una carpeta results/2026-04-16.

Las evidencias que usaremos para encontrar los genes són secuencias de proteínas que esperamos encontrar codificadas en los cóntigos. Normalmente usaríamos las proteínas conocidas de alguna especie próxima. Usaremos las 6023 proteínas que sabemos que codifica el cromosoma 4 de Arabidopsis thalina. Las podéis descargar de Uniprot

# Programas

Los programas que no utilizaremos (porque no están instalados y son difíciles de instalar son RepeatModeler (Flynn et al. 2020), RepeatMasker, y GALBA (Bruna et al. 2023). Cada uno de ellos, a su vez, utiliza otros.

# Resultados

Al descargar las proteínas del cromosoma 4 de A. thaliana, el archivo FASTA contiene cabeceras demasiado extensas. Para facilitar el trabajo de GALBA vamos a modificar las cabeceras o nombres de las secuencias. De líneas como esta:

Al descargar las proteínas del cromosoma 4 de A. thaliana, el archivo FASTA contiene cabeceras demasiado extensas. Para facilitar el trabajo de GALBA vamos a modificar las cabeceras o nombres de las secuencias. De líneas como esta:

> sp\|Q0WVX5\|SSY4_ARATH Probable starch synthase 4, chloroplastic/amyloplastic OS=Arabidopsis thaliana OX=3702 GN=SS4 PE=1 SV=1

## Ejercicio 1

Sabiendo que una forma de hacerlo es la siguiente, incluye la orden en un bloque de Bash de tu documento de Quarto de tal manera que el archivo de entrada esté en tu carpeta data y el de salida en la misma carpeta de trabajo de la práctica actual, y además, que sólo se ejecute si el archivo de salida proteinas.fasta no existe.

```{bash}
if [ ! -e proteinas.fasta ]; then
  cat ../2026-04-21/uniprotkb_proteome_UP000006548_AND_prot_2026_04_21.fasta | gawk '(/^>/){split($1, A, /\|/); print ">" A[2]}(/^[^>]/){print $0}'

fi
```

```{bash}
if [ ! -e proteinas.fasta ]; then
  gawk '(/^>/){split($1, A, /\|/); print ">" A[2]}(/^[^>]/){print $0}' ../2026-04-21/uniprotkb_proteome_UP000006548_AND_prot_2026_04_21.fasta > proteinas.fasta

fi
```

# Análisis de los resultados de RepeatModeler

Utiliza como input sólo el ensamblaje, para identificar los elementos repetitivos que pueda haber. Genera, entre otras cosas, un archivo FASTA con las secuencias consenso de las familias de elementos transponibles identificadas. Este archivo FASTA se puede usar después para enmascarar el genoma.

## Ejercicio 2

Explora los resultados de RepeatModeler y trata de contestar las preguntas siguientes.

1.  ¿Cuántas familias de elementos transponibles se han encontrado? En el archivo At4-families:24

```{bash}
grep -c "^>" RepeatModelerResults/At4-families.fa
```

2.  ¿Cuánto duró la ejecución del programa? Program Time: 01:02:16 (run.log). Este es el tiempo total compuesto de 3 rondas.

3.  ¿Cuál dirías que es el archivo de salida más importante? Si lo que euieres es anotar lo importante son las secuencias de alineamiento. Aunque, el run nos da información de como se ha ejecutado y aporta información complementaria relevante.

# Suavizar la máscara

RepeatMasker fue ejecutado así:

RepeatMasker -lib At4-families.fa -dir RM01 -gtf ../../data/At4.fa

Encontrarás la carpeta (comprimida) de resultados de RepeatMasker en el aula virtual. Descárgala y descomprimela en la carpeta de trabajo actual. La versión enmascarada tiene una máscara dura (RepeatMasker ha sustituído todos los elementos trasponibles y repeticiones por Ns), con lo que se ha perdido la información de la secuencia original en esas regiones. El programa GALBA recomienda partir de un ensamblaje con máscara suave, donde las regiones repetitivas están marcadas con letra minúscula. Para convertir la máscara dura en una máscara suave, utilizaremos bedtools.

## Ejercicio 3

1.  Instala el programa bedtools siguiendo las instrucciones oportunas para tu sistema en la página oficial mv bedtools.static bedtools/ cambio de nombre el ejecutable y luego dar el permiso de ejecutar. chmod u+x bedtools

2.  Utiliza el ensamblaje original como archivo FASTA de entrada y el archivo GFF que ha producido RepetaMasker como coordenadas de las regiones a enmascarar. Lee el manual de bedtools maskfasta en este enlace y genera el ensamblaje con máscara suave llamado At4.soft.fa.

```{bash}
../../../../bin/bedtools maskfasta -fi ../2026-04-16/asm1/At4.fa -bed RepeatMaskerResults/RM01/At4.fa.out.gff -fo At4.soft.fa
```

# GALBA

Para ejecutar GALBA ha sido necesario crear algunas variables de entorno que indican donde puede GALBA encontrar un par de ejecutables más. Para facilitar la reproducibilidad, este tipo de definiciones deben aparecer al principio del bloque, donde son más visibles, para que sean fácilmente modificadas cuando las órdenes vayan a ejecutarse en otro ordenador.

## Ejercicio 4

Incluye en tu documento de Quarto un bloque de código (pero no ejecutable, con la opción eval: false) como el anterior, donde los caminos TSERBA y a MINIPROTHINT se correspondan con tu propia carpeta bin, aunque no los tengas instalados.

```{bash}
#| eval: false
export TSEBRA_PATH=/home/avril/bin/TSEBRA/bin/
export MINIPROTHINT_PATH=/home/avril/bin/miniprothint/

galba.pl --species="Arabidopsis thaliana" \
         --genome=At4.soft.fa \
         --prot_seq=proteinas.fasta
```
no se ejecutan porque no tengo estos programas instalados
## Ejercicio 5

Échales un vistazo a los archivos de salida de GALBA y trata de sacar algo en claro. Galba usa miniprot y las evidencias proporcionado y las mapea frente ensamblaje anterior. Uso de Augustus que identifique bien los genes. Con varias rondas refina.

Modeler:Los archivos nhr, nin: son base de datos de blast a partir del ensamblaje para buscar rápido entre ellos. At4-families.fa (secuencias concenso de cada familia identificada)/.stk(alineamientos)/.log LTR/Gypsy el elemento transponible que es con la scecuencias que se parecen y la secuencias que se parecen. El archivo stk tiene el alinemaiento para cada familia. Se puede ver en gráfica los tamaños de cada familia (desconocido es el mayor) RepeatModeler no se suele hacer (solo en especie desconocidos en donde pued ehaber elementos transponible sdesconocidos y hay que modelar). Sino usar los datos ya secuenciados y anotados.

RepeatMasker. AtAt4.fa.masked pone N en los nt de elementos transponibles. El de salida gff permite convertir las N mayúsculas en minúsculas. En donde dice las coordenadas de cada elemnto transponible. Una vez enmascarado suave pasar a GABA

GAlBA: lenguage de Pearl.Usa Augustus para predicir (inteligencia de marchine learning). Prot_seq_all: todas las proteínas predichas por galba a partir del genoma annotado. Especie pertenece (para entrenar augustus), el genoma enmascarado + evidencias (proteinas de especie muy próxima). GABAlog: toda la historia a qué hora lo que hecho configuración, procesar alineamiento y generar el conjunto genes de entrenamiento de augustus el cual refinado de predicción de genes. Uso de augustos de una especie para predecir en especie próxima. GABA.gtf: cóntigo en donde encontrado que tipo de cosa identificada (empieza y termina), puntuación, la cadena, a que transcripto o gen pertenece. Prediccion exacta empieza cadena codif exones e intrones. Se puede confundir pero la informaciones fundamental. También dan los datos de que hay que citar.

## Ejercicio 6

Si quieres, puedes intentar instalar GALBA en tu ordenador, tomando nota de las dificultades con las que te encuentras.
